apiVersion: apps/v1
kind: Deployment
metadata:
  name: codo-cmdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codo-cmdb
  template:
    metadata:
      labels:
        app: codo-cmdb
    spec:
      containers:
      - name: codo-cmdb
        image: harbor-k8s.shinezone.com/ops/codo-cmdb:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
#        lifecycle:
#          postStart:
#            exec:
#              command: ['/bin/sh', '-c', 'sed -i "s/s_hostname/$(hostname)/" /data1/www/templates/app.html']
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
            - name: cmdbconf
              mountPath: /var/www/CMDB/cmdb.conf
              subPath: cmdb.conf  #以文件的形式挂载
              readOnly: true
            - name: cmdbnginx
              mountPath: /etc/nginx/conf.d/nginx_cmdb.conf
              subPath: nginx_cmdb.conf
              readOnly: true

      volumes:
        - name: cmdbconf
          configMap:
            name: cmdb-conf   #configmap要提前创建好  kubectl create configmap cmdb-conf --from-file=./cmdb.conf -n qa
        - name: cmdbnginx
          configMap:
            name: cmdb-nginx-conf  # kubectl create configmap cmdb-nginx-conf --from-file=./cmdb-nginx-conf -n qa

---
apiVersion: v1
kind: Service
metadata:
  name: codo-cmdb
  labels:
    app: codo-cmdb
spec:
  selector:
    app: codo-cmdb
  #type: NodePort
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codo-cmdb-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: <DOMAIN>
    http:
      paths:
      - path:
        backend:
          serviceName: codo-cmdb
          servicePort: 80